# Generated by Django 6.0.1 on 2026-01-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convuser',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
