# Generated by Django 5.2.7 on 2025-12-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_likedcomment_comment_likes_repost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-count', 'name'],
            },
        ),
    ]
