# Generated by Django 5.2.7 on 2025-12-15 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Visite', 'verbose_name_plural': 'Visites'},
        ),
        migrations.AddField(
            model_name='visit',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='Connecté'),
        ),
        migrations.AddField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='path',
            field=models.TextField(blank=True, null=True, verbose_name='Chemin'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date et heure'),
        ),
    ]
